### Авторизация
POST {{host}}/rest/signOn?username=test&password=test&fullName=Ivan&city=Salekhard&birthDay=22.05.2010&email=test123789@test.ru
Content-Type: 'application/json'

{
    "username": "test",
    "password": "test',
    "fullName": "Ivan",
    "city": "Salekhard",
    "birthDay": "22.05.2010",
    "email": "test@test.ru"
}


### Авторизация 2.0
POST {{host}}/rest/signOn
Content-Type: 'application/json'

{
    "username": "user555",
    "password": "user1',
    "firstName": "Иван",
    "lastName": "Васильевич",
    "age": 17,
    "studyPlace": 1
}